export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS';
export const ADD_SCORE_ERROR = 'ADD_SCORE_ERROR';
export const FETCH_USERS_LIST_LOADING = 'FETCH_USERS_LIST_LOADING';
export const FETCH_USERS_LIST_SUCCESS = 'FETCH_USERS_LIST_SUCCESS';
export const FETCH_USERS_LIST_ERROR = 'FETCH_USERS_LIST_ERROR';